export const SORT_BY_ASC = "SORT_BY_ASC"
export const SORT_BY_DSC = "SORT_BY_DSC"
export const SORT_BY_DATE = "SORT_BY_DATE"
export const SORT_BY_QUALITY = "SORT_BY_QUALITY"
export const FILTER = "FILTER_EXPLICIT"
